### ISSUE TITLE
net-snmp IP-FORWARD-MIB error converting

### ISSUE THREAD

**Issue by robgil** [logstash-plugins/logstash-input-snmp#13]
I'm not sure if this might break things, but seems to be throwing an error on the net-snmp IP-FORWARD-MIB.txt conversion. This is the latest `brew install net-snmp` and `brew install libsmi`.

```
$ smidump -k -f python ./IP-FORWARD-MIB.txt > ~/IP-FORWARD-MIB.dic
./IP-FORWARD-MIB.txt:214: index element `inetCidrRoutePolicy' of row `inetCidrRouteEntry' should but cannot have a size restriction
```

**Comment by robgil** [comment]
`smidump -k -f python ./IP-MIB.txt > ~/IP-MIB.dic` came out clean.

**Comment by robgil** [comment]
Similar error on `IF-MIB`.
```
$ smidump -k -f python ./IF-MIB.txt > ~/IF-MIB.dic
./IF-MIB.txt:1065: index element `ifRcvAddressAddress' of row `ifRcvAddressEntry' must have a size restriction
```

**Comment by colinsurprenant** [comment]
@robgil I also noticed such errors/warnings and not sure either about the actual impact, I will have to verify the generated dic vs the actual ASN see if something is missing or doesn't look right. So far it did not seems to affect any of my tests.

**Comment by colinsurprenant** [comment]
I searched online and looked at the generated dic files and it seems that the "size restriction" errors will be harmless and can be ignored.

**Comment by colinsurprenant** [comment]
@robgil 

So after doing some more investigations these warning are harmless in our context. I suggest using the `--level=1` option to ignore non-fatal errors. Also more information on using `smidump` here https://github.com/logstash-plugins/logstash-input-snmp/issues/16#issuecomment-418890883

We will produce better documentation around this process. Note that in #25 we are going to include all `ietf` MIBs to make things easier to get started.  

Let me know if we can close this.
