### ISSUE TITLE
Timeout sending SNMP GET doesn't specify host address in log

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#15]
Currently running beta4 of this plugin and ran across the interesting problem that when you try and poll an unresponsive IP address, you get the following error:

`[2018-07-10T02:03:54,410][ERROR][logstash.inputs.snmp     ] error invoking get operation on OIDs: ["1.3.6.1.2.1.1.1.0", "1.3.6.1.2.1.1.3.0", "1.3.6.1.2.1.1.5.0"], ignoring {:exception=>#<LogStash::SnmpClientError: timeout sending snmp get request>, :backtrace=> <removed>}
`

With only a handful of hosts this wouldn't be so bad, but in much larger deployments, this would make it hard to identify that single errant host.

By including `#{definition[:host_address]}` in the logger.error lines in snmp.rb, we could get a more helpful error:
`[2018-07-10T02:13:26,245][ERROR][logstash.inputs.snmp     ] error invoking get operation on 192.168.192.168 for OIDs: ["1.3.6.1.2.1.1.1.0", "1.3.6.1.2.1.1.3.0", "1.3.6.1.2.1.1.5.0"], ignoring {:exception=>#<LogStash::SnmpClientError: timeout sending snmp get request>, :backtrace=> <removed>}
`

On a slightly related note, do we need to keep the backtrace for all errors or can we split out some of the more obvious ones like no response, can't resolve, invalid IP format and send a more crafted logger.error that doesn't include the mountain of backtrace information every polling cycle?

**Comment by colinsurprenant** [comment]
@axrayn thanks for opening this issue. Great suggestions, will add the host info. As for the backtrace, yes, for timeout, I agree we don't need the backtrace info. Will verify the other logging too.

**Comment by colinsurprenant** [comment]
This was solved by #27
