### ISSUE TITLE
PDU/PDUFactory as optional params

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#18]
Morning @colinsurprenant,

I'm new to JRuby so apologies in advance if I get some of the terminology wrong here. 

We're definitely keen to use this plugin proverbially 'in anger' but we have some time and technical constraints so I wrote SNMPv3 support for this plugin by creating an 'SnmpClientV3' class as a subclass of SnmpClient. In doing this though, I found that instead of being able to just inherit the get/walk functions, I've had to redefine them because of the PDU vs ScopedPDU differences between SNMPv1/2c and SNMPv3 which I don't think is a great step moving forward because it would mean every change to one of these methods would then need to be made in two places instead of one.

I was just wondering if it would be possible to change the get and walk methods to include *pdu and *pdufactory optional parameters respectively and the associated code within the methods to check for this?

If the get method is updated to `def get(oids, strip_root = 0, *pdu)` then I could simply define the get method in the SnmpClientV3 to create the ScopedPDU object and then call super(oid, strip_root, pdu) to pass all the params through to the get method from the SnmpClient class and I'm guessing the get method would then simply need to be updated to something like `pdu = pdu || PDU.new` ?

**Comment by colinsurprenant** [comment]
Great stuff @axrayn - seems to make sense, let me check that  and get back to you. Will you be willing to contribute back your SNMPv3 code after? totally fine if you don't/can't but if you do I'll wait for that before doing more on V3 on my side.

**Comment by axrayn** [comment]
Happy to contribute back, there's still a bunch I need to clean up in it first though. I've uploaded my latest version to the fork here: https://github.com/axrayn/logstash-input-snmp

I ended up adding a v3_users config array so users could specify multiple v3 auth configurations that are then just called from the host config by the community value when the host version is set to 3.

Hopefully this also means (haven't tested it yet) that users could use values from a Logstash keystore if they're in the right format, e.g. `v3_users => [${CISCO_V3USER}, ${F5_V3USER}]`
if the keystore value is set to `{'name => "ciscosnmpv3" auth_protocol => "sha" auth_pass => "ShaPass" priv_protocol => "aes256" priv_pass => "AesPass" "auth_level" => "authNoPriv"}`

**Comment by colinsurprenant** [comment]
Thanks @axrayn will look it up!

**Comment by axrayn** [comment]
Happy to close this issue now given #27
