### ISSUE TITLE
CISCO MIB's converting error

### ISSUE THREAD

**Issue by ragurajendran86** [logstash-plugins/logstash-input-snmp#19]
When i try to convert the cisco MIB to DIC, every CISCO MIB file has dependency on other MIB's inernally. During the conversion its not able to load the depency and throws errors like below.

For Example,
smidump --level=6 -k -f python ./CISCO-PROCESS-MIB_my.mib > CISCO-PROCESS-MIB_my.dic
./CISCO-PROCESS-MIB_my.mib:40: warning: `Unsigned64' is a base type in SPPI
./CISCO-PROCESS-MIB_my.mib:41: failed to locate MIB module `CISCO-TC'
./CISCO-PROCESS-MIB_my.mib:43: failed to locate MIB module `CISCO-SMI'
./CISCO-PROCESS-MIB_my.mib:158: unknown object identifier label `ciscoMgmt'
./CISCO-PROCESS-MIB_my.mib:264: type `EntPhysicalIndexOrZero' of node `cpmCPUTotalPhysicalIndex' does not resolve to a known base type
./CISCO-PROCESS-MIB_my.mib:617: type `EntPhysicalIndexOrZero' of node `cpmCorePhysicalIndex' does not resolve to a known base type
./CISCO-PROCESS-MIB_my.mib:699: warning: index element `cpmProcessPID' of row `cpmProcessEntry' should be not-accessible in SMIv2 MIB
./CISCO-PROCESS-MIB_my.mib:223: unknown type `EntPhysicalIndexOrZero'
smidump: module `./CISCO-PROCESS-MIB_my.mib' contains errors, expect flawed output

I am using libsmi 0.4.8v. Any way to resolve the dependency during the conversion?

**Comment by colinsurprenant** [comment]
Hi @ragurajendran86, thanks for reporting this. I found the CISCO mibs [in this repo](https://github.com/trevoro/snmp-mibs) and was able to reproduce your problem and find the solution.

What is happening is that the `CISCO-PROCESS-MIB` need to include the dependant mibs `CISCO-TC` and `CISCO-SMI` but `smidump` only looks for mib dependencies in its pre-configured path lists  as defined [in the doc](https://www.ibr.cs.tu-bs.de/projects/libsmi/smi_config.html?lang=de) in the "MODULES LOCATIONS" section. 

There are 2 ways to easily fix the problem. Let's say you are within your mibs dir located at `/path/to/mibs/`:

1. Set the `SMIPATH` env var with the path to your mibs with something like this. 
```
$ SMIPATH=":/path/to/mibs/" smidump -k -f python CISCO-PROCESS-MIB.mib > CISCO-PROCESS-MIB_my.dic
```
Note the prepended colon `:`. Per the doc:
> The ‘path’ command argument and the environment variable either start with a path separator character (‘:’ on UNIX-like systems, ‘;’ on MS-Windows systems) to append to the path, or end with a path separator character to prepend to the path, or otherwise completely replace the path.

2. Create a configuration file, say `smi.conf` with the path option.

```
path :/path/to/mibs/
```
and use that config with `smidump`:
```
$ smidump -c smi.conf -k -f python CISCO-PROCESS-MIB.mib > CISCO-PROCESS-MIB_my.dic
```

Let me know if this helps.

**Comment by colinsurprenant** [comment]
@ragurajendran86 these are warnings and I do not think will have consequences for OID path resolution. Did you try using your converted mibs? did you notice any problem?

**Comment by colinsurprenant** [comment]
Also note that after some investigation, using `--level=6` is way too verbose in our context and for how we use the MIBs.  Basically all "warnings" should be armless.

Using `--level=1` is sufficient for spotting important notices. 

@ragurajendran86 Let me know how this is working for you.

**Comment by redcinelli** [comment]
@colinsurprenant Thanks a lot for [your solution](https://github.com/logstash-plugins/logstash-input-snmp/issues/19#issuecomment-418857578) we managed to make it work.

I would just add that please be aware of special character in your path (`space`, `&` ...) it took us quite a while to understand the issue.

**Comment by edmocosta** [comment]
Closing this issue as https://github.com/logstash-plugins/logstash-input-snmp/issues/19#issuecomment-418857578 seems to solve the problem. That solution was also added to the troubleshooting section on the plugin's doc (https://github.com/logstash-plugins/logstash-input-snmp/pull/112).
