### ISSUE TITLE
Need coerce handler for syntax 129

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#31]
When performing a get request on certain OIDs, I'm getting errors with the following in the traceback:

`<LogStash::SnmpClientError: unknown variable syntax 129, NoSuchInstance>`

Simplest solution would be to update base_client.rb and change line 127 from:
`when BER::NOSUCHOBJECT` 
to
`when BER::NOSUCHOBJECT, BER::NOSUCHINSTANCE`

**Comment by colinsurprenant** [comment]
PR in #32
