### ISSUE TITLE
Plugin not recognized

### ISSUE THREAD

**Issue by prakash1243** [logstash-plugins/logstash-input-snmp#33]
I tried installing the plugin, but I get this error message when running the config. 

> [2018-10-15T17:18:18,820][ERROR][logstash.plugins.registry] Problems loading a p
lugin with {:type=>"input", :name=>"snmp", :path=>"logstash/inputs/snmp", :error
_message=>"\n\n\tyou might need to reinstall the gem which depends on the missin
g jar or in case there is Jars.lock then resolve the jars with `lock_jars` comma
nd\n\nno such file to load -- org/snmp4j/snmp4j/2.5.11/snmp4j-2.5.11 (LoadError)
", :error_class=>RuntimeError, :error_backtrace=>["C:/logstash/vendor/bundle/jru
by/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:344:in `do_require
'", "C:/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_
dependencies.rb:253:in `block in require_jar'", "C:/logstash/vendor/bundle/jruby
/2.3.0/gems/jar-dependencies-0.3.12/lib/jar_dependencies.rb:295:in `require_jar_
with_block'", "C:/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.1
2/lib/jar_dependencies.rb:252:in `require_jar'", "C:/logstash/lib/bootstrap/patc
hes/jar_dependencies.rb:6:in `require_jar'", "C:/logstash/vendor/bundle/jruby/2.
3.0/gems/logstash-input-snmp-0.1.0.beta5/lib/logstash-input-snmp_jars.rb:4:in `<
main>'", "org/jruby/RubyKernel.java:955:in `require'", "C:/logstash/vendor/bundl
e/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "C:/logstash
/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta5/lib/logstash/inp
uts/snmp/client.rb:1:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'",
 "uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative'", "C:/logstas
h/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1.0.beta5/lib/logstash/in
puts/snmp/client.rb:2:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'"
, "C:/logstash/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:
in `require'", "C:/logstash/logstash-core/lib/logstash/plugins/registry.rb:162:i
n `legacy_lookup'", "C:/logstash/logstash-core/lib/logstash/plugins/registry.rb:
140:in `lookup'", "C:/logstash/logstash-core/lib/logstash/plugins/registry.rb:18
7:in `lookup_pipeline_plugin'", "C:/logstash/logstash-core/lib/logstash/plugin.r
b:140:in `lookup'", "C:/logstash/logstash-core/lib/logstash/plugins/plugin_facto
ry.rb:82:in `plugin'", "C:/logstash/logstash-core/lib/logstash/pipeline.rb:114:i
n `plugin'", "C:/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-snmp-0.1
.0.beta5/lib/logstash/inputs/snmp.rb:1:in `<eval>'", "org/jruby/RubyKernel.java:
994:in `eval'", "C:/logstash/logstash-core/lib/logstash/pipeline.rb:86:in `initi
alize'", "C:/logstash/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'
", "C:/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `exec
ute'", "C:/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converg
e_state'", "C:/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelin
es'", "C:/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge
_state'", "org/jruby/RubyArray.java:1734:in `each'", "C:/logstash/logstash-core/
lib/logstash/agent.rb:319:in `converge_state'", "C:/logstash/logstash-core/lib/l
ogstash/agent.rb:166:in `block in converge_state_and_update'", "C:/logstash/logs
tash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "C:/logstash/logstash-
core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "C:/logstash/log
stash-core/lib/logstash/agent.rb:90:in `execute'", "C:/logstash/logstash-core/li
b/logstash/runner.rb:343:in `block in execute'", "C:/logstash/vendor/bundle/jrub
y/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
[2018-10-15T17:18:18,860][ERROR][logstash.agent           ] Failed to execute ac
tion {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"L
ogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 's
nmp'. Are you sure this is correct? Trying to load the snmp input plugin resulte
d in this error: Problems loading the requested plugin named snmp of type input.
 Error: RuntimeError \n\n\tyou might need to reinstall the gem which depends on
the missing jar or in case there is Jars.lock then resolve the jars with `lock_j
ars` command\n\nno such file to load -- org/snmp4j/snmp4j/2.5.11/snmp4j-2.5.11 (
LoadError)", :backtrace=>["C:/logstash/logstash-core/lib/logstash/plugins/regist
ry.rb:192:in `lookup_pipeline_plugin'", "C:/logstash/logstash-core/lib/logstash/
plugin.rb:140:in `lookup'", "C:/logstash/logstash-core/lib/logstash/plugins/plug
in_factory.rb:82:in `plugin'", "C:/logstash/logstash-core/lib/logstash/pipeline.
rb:114:in `plugin'", "(eval):8:in `<eval>'", "org/jruby/RubyKernel.java:994:in `
eval'", "C:/logstash/logstash-core/lib/logstash/pipeline.rb:86:in `initialize'",
 "C:/logstash/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'", "C:/l
ogstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "
C:/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'
", "C:/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "C
:/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'"
, "org/jruby/RubyArray.java:1734:in `each'", "C:/logstash/logstash-core/lib/logs
tash/agent.rb:319:in `converge_state'", "C:/logstash/logstash-core/lib/logstash/
agent.rb:166:in `block in converge_state_and_update'", "C:/logstash/logstash-cor
e/lib/logstash/agent.rb:141:in `with_pipelines'", "C:/logstash/logstash-core/lib
/logstash/agent.rb:164:in `converge_state_and_update'", "C:/logstash/logstash-co
re/lib/logstash/agent.rb:90:in `execute'", "C:/logstash/logstash-core/lib/logsta
sh/runner.rb:343:in `block in execute'", "C:/logstash/vendor/bundle/jruby/2.3.0/
gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}

**Comment by axrayn** [comment]
Hi @prakash1243 

As I mentioned over on the Discuss forum, how did you install the plugin?

I tested it this morning with:
`bin/logstash-plugin install --version 0.1.0-beta5 lostash-input-snmp`

amd it correctly installs the dependencies

**Comment by prakash1243** [comment]
Yes, I would need to put JARS_SKIP=true as an enviornment variable, then it started working fine. thanks !
