### ISSUE TITLE
Change to the oid_root_skip functionality

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#34]
Currenly oid_root_skip expects an integer for the number of branches to skip when returning the mapped OID.

Would it be possibly to specify this as a negative number and have it return only this many fields regardless of the total number of branches in the OID?

e.g. If you wanted to walk both the ifTable and ifXTable in the same walk and collect the description and alias fields respectively:
`1.3.6.1.2.1.2.2.1.2 = iso.org.dod.internet.mgmt.mib-2.interfaces.ifTable.ifEntry.ifDescr`
`1.3.6.1.2.1.31.1.1.1.18 = iso.org.dod.internet.mgmt.mib-2.ifMIB.ifMIBObjects.ifXTable.ifXEntry.ifAlias`

As it currently stands, the best result you could send back without needing distinct snmp inputs is:
`ifDescr.21 => "Realtek Semiconductor Co."`
`ifXEntry.ifAlias.21 => "eth0"`

If we could specify oid_root_skip as "-2" then we could have it return:
`ifDescr.21 => "Realtek Semiconductor Co."`
`ifAlias.21 => "eth0"`

Or if we can't use negatives, possibly include it as a new config variable that is mutually exclusive to oid_root_skip?

**Comment by colinsurprenant** [comment]
Also a very good idea! I think I prefer a separate option. Will put that for post-1.0.

**Comment by axrayn** [comment]
@colinsurprenant I've got this quick one coded up already, just needs some more testing, Do you have a preference for the config option name? I'd used oid_root_tail as a placeholder. I've got it built as mutually exclusive with oid_root_skip so that specifying both will raise a ConfigurationError.

**Comment by colinsurprenant** [comment]
@axrayn great!  or maybe `oid_path_length` ?

**Comment by axrayn** [comment]
Added in #59

**Comment by colinsurprenant** [comment]
Merged! Closing.
