### ISSUE TITLE
Config option to specify a target field

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-input-snmp#50]
Several other plugins provide a config option to specify a target field for the output data rather than simply storing in the document root.

This would both be useful to allow users to format their data structure easier, plus will go towards consistency on some standard config options.

metadata and other general host details could be in the document root but the actual SNMP results could go to the target field.

Optionally, this could be done per get/walk/tables config item rather than a global option so users could store the distinct results under different hierarchies.

**Comment by colinsurprenant** [comment]
+1
