### ISSUE TITLE
oid_root_skip noted as boolean instead of number

### ISSUE THREAD

**Issue by igorrev** [logstash-plugins/logstash-input-snmp#56]
**oid_root_skip** option is noted as boolean in [SNMP Input Configuration Options](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-snmp.html#plugins-inputs-snmp-options) section. But actually it's number.

**Comment by axrayn** [comment]
Nice catch @igorrev! I'll fix that up as a part of the general doc update for #55

**Comment by colinsurprenant** [comment]
Thanks @igorrev @axrayn  - #57 fixes this, closing.
