### ISSUE TITLE
Add metadata to fields

### ISSUE THREAD

**Issue by ciscojer** [logstash-plugins/logstash-input-snmp#6]
Hi I'm using this plugin like to poll a single OID for the temperature value from 2 switches. When I have multiple "hosts" defined, there is no way to tell which switch the value comes from. 

Is it possible to add metadata to the input to include the value of "host" in the event? 

Thx, Jeremy

Logstash input:
input {
  snmp {
    walk => ["1.3.6.1.4.1.9.9.13.1.3.1.3"]
    #mib_paths => ["path/to/RFC1213-MIB.dic"]
        hosts => [{host => "udp:10.10.10.230/161" community => "public"},{host => "udp:10.10.10.44/161" community => "public"}]
    type => "snmp"
  }
}

Results from first device showing OID value of 62

{
  "_index": "logstash-2018.05.28",
  "_type": "doc",
  "_id": "VQdkpGMBNA17SEvAjCBG",
  "_version": 1,
  "_score": null,
  "_source": {
    "1.3.6.1.4.1.9.9.13.1.3.1.3.1004": 62,
    "@timestamp": "2018-05-28T01:37:22.904Z",
    "@version": "1",
    "type": "snmp"
  },
  "fields": {
    "@timestamp": [
      "2018-05-28T01:37:22.904Z"
    ]
  },
  "highlight": {
    "type": [
      "@kibana-highlighted-field@snmp@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1527471442904
  ]
}

Results from second device showing OID value of 60

{
  "_index": "logstash-2018.05.28",
  "_type": "doc",
  "_id": "VAdkpGMBNA17SEvAjCA7",
  "_version": 1,
  "_score": null,
  "_source": {
    "1.3.6.1.4.1.9.9.13.1.3.1.3.1004": 60,
    "@timestamp": "2018-05-28T01:37:22.901Z",
    "@version": "1",
    "type": "snmp"
  },
  "fields": {
    "@timestamp": [
      "2018-05-28T01:37:22.901Z"
    ]
  },
  "highlight": {
    "type": [
      "@kibana-highlighted-field@snmp@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1527471442901
  ]
}

**Comment by colinsurprenant** [comment]
@ciscojer thanks for your suggestion - indeed we need to add this! Let me know what you think about this idea: The event `@metadata` field could be populated with the `host_protocol`, `host_address`, `host_port`, `host_community` fields and the `add_field` config option could be used to add a `host` field which could be a combination of any of the `@metadata` fields for example:
```
input {
  snmp {
    walk => ["1.3.6.1.4.1.9.9.13.1.3.1.3"]
    hosts => [{host => "udp:10.10.10.230/161" community => "public"}, {host => "udp:10.10.10.44/161" community => "public"}]
    type => "snmp"
    add_field => { "host" => %{[@metadata][host_address]}" }
  }
}
```

I think we could make this the default behaviour :
```
add_field => { "host" => %{[@metadata][host_address]}" }
``` 


but it would be possible to overwrite with something like that for example:
```
add_field => { "host" => %{[@metadata][host_protocol]}:%{[@metadata][host_address]}/%{[@metadata][host_port]},%{[@metadata][host_community]}" }
```

WDYT?

**Comment by colinsurprenant** [comment]
@ciscojer I forgot to mention that as a temporary workaround you can configure multiple inputs with one host per input and then add a field or a tag per input to identify your host.

**Comment by ciscojer** [comment]
Hi @colinsurprenant thanks for the quick reply. Yes adding @metadata like that is ideal as having host_address and host_community will be very useful in my environment. I was able to work around the limitation by having 2 inputs (one for each host) and then adding some tags with the "tags" option as you suggested.

**Comment by colinsurprenant** [comment]
@ciscojer great! I am planning on pushing a PR for this today and will appreciate your feedback!

**Comment by colinsurprenant** [comment]
pushed #7

**Comment by colinsurprenant** [comment]
@ciscojer merged #7. you can update plugin to 0.1.0.beta2 and let me know if that works for you!

**Comment by ciscojer** [comment]
Hi @colinsurprenant thanks for the quick fix. I've upgraded to beta2 and see the "host" field in the event now -  Thanks!

{
  "_index": "logstash-2018.05.30",
  "_type": "doc",
  "_id": "SEMOs2MBNA17SEvAVkwk",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-05-30T21:57:31.195Z",
    "1.3.6.1.4.1.9.9.13.1.3.1.3.1004": 59,
    "@version": "1",
    "type": "snmp",
    "host": "cat3560-closet"
  },
  "fields": {
    "@timestamp": [
      "2018-05-30T21:57:31.195Z"
    ]
  },
  "highlight": {
    "type": [
      "@kibana-highlighted-field@snmp@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1527717451195
  ]
}

Thx, Jeremy

**Comment by colinsurprenant** [comment]
Perfect! will go ahead and close this issue. Thanks again for your help @ciscojer !
