### ISSUE TITLE
integration tests/specs using docker and net-snmp

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-snmp#87]
While working on SNMPv3 PR #84 my testing setup consisted of manually spinning docker containers made from bare Ubuntu images with the net-snmp package installed. I manually edited the net-snmp configs in the running containers to create multiple snmp hosts that I could perform tests against.

I think we should use that same idea for adding integration tests and encode the different testing scenarios I used in #80 and #84. 

As an example the elasticsearch input/output/filter plugins and logstash-integration-jdbc uses docker containers to run the services required for the integration tests.

**Comment by kaisecheng** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-snmp/pull/90
