### ISSUE TITLE
Documentation on how to cluster?

### ISSUE THREAD

**Issue by loganmc10** [logstash-plugins/logstash-input-snmp#92]
Is it possible to have a group/cluster of logstash instances polling devices based on a common configuration? If so, is there documentation about this?

It's easy to use a load balancer to distribute things like SNMP traps to different logstash instances, but I'm wondering how I load balance outbound SNMP polling?

**Comment by craigers521** [comment]
@loganmc10 - did you come up with a solution for this? I am also trying to figure this out myself with docker swarm... for pure ingestion its easy to LB the traffic, but when logstash is polling SNMP im not sure how to divy up the work unless i just use a seperate config file for each logstash instance, and write some script to dynamically generate the config based on number of workers... I'd be curious to know if you found a solution...
